apiVersion: v1
kind: Service
metadata:
  name: webdav-service
  labels:
    app: webdav-service
spec:
  ports:
  - port: 8080
  selector:
    app: webdav-service
  clusterIP: None
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: webdav-service
  labels:
    app: webdav-service
spec:
  selector:
     app: webdav-service
  template:
    metadata:
      labels:
        app: webdav-service
    spec:
      containers:
      - image: craigwillis/wsgidav:latest
        name: wsgidav-server
        ports:
        - containerPort: 8080
          name: webdav-service
